export const $GLOABL_PREFIX$ = 'GLOBAL'

export const FETCH_LIST_SUCCESS = '/FETCH_LIST_SUCCESS'
export const APPEND_LIST_SUCCESS = '/APPEND_LIST_SUCCESS'
export const FETCH_DETAILS_SUCCESS = '/FETCH_DETAILS_SUCCESS'
export const START_LOADING = '/START_LOADING'
export const FINISH_LOADING = '/START_LOADING'
