export const $GLOABL_PREFIX$ = 'GLOBAL'

export const SET_LIST_REQUEST_TYPE = '/SET_LIST_REQUEST_TYPE'
export const SET_NO_MORE = '/SET_NO_MORE'
export const FETCH_LIST_SUCCESS = '/FETCH_LIST_SUCCESS'
export const APPEND_LIST_SUCCESS = '/APPEND_LIST_SUCCESS'
export const FETCH_DETAILS_SUCCESS = '/FETCH_DETAILS_SUCCESS'
export const START_LOADING = '/START_LOADING'
export const FINISH_LOADING = '/FINISH_LOADING'
export const SHOW_LEFT_POPUP = '/SHOW_LEFT_POPUP'
export const HIDE_LEFT_POPUP = '/HIDE_LEFT_POPUP'

